# Actividad 2

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import plotly.graph_objects as go
import time
import os
import pickle
from math import radians, sin, cos, sqrt, atan2

from my_lib.utility import *

## ciudades

In [3]:
ciudades18 = {
    'Ciudad': ['Mexico City', 'Merida', 'Buenos Aires', 'Quito', 'Washington D.C.', 
               'New York', 'Miami', 'Monterrey', 'Panama City', 'San Salvador',
               'Managua', 'Brazilia', 'Mendoza', 'Caracas', 'Montevideo', 
               'Guadalajara', 'Boston', 'Bogotá'],
    'Latitud': [19.4326, 20.9674, -34.6037, -0.1807, 38.9072, 
                40.7128, 25.7617, 25.6866, 8.9824, 13.6929, 
                12.1140, -15.8267, -32.8895, 10.4806, -34.9011, 
                20.6597, 42.3601, 4.7110],
    'Longitud': [-99.1332, -89.5926, -58.3816, -78.4678, -77.0369, 
                 -74.0060, -80.1918, -100.3161, -79.5199, -89.2182, 
                 -86.2362, -47.9218, -68.8458, -66.9036, -56.1645, 
                 -103.3496, -71.0589, -74.0721]
}

## codificación del dominio

In [4]:
df_ciudades = pd.DataFrame(ciudades18)


nombre_ciudades = np.array(ciudades18['Ciudad'])

id_ciudades = np.arange(nombre_ciudades.shape[0])
bin_ciudades = binarizar(datos=id_ciudades,nbites=3)

ciudades = np.zeros((nombre_ciudades.shape[0],4),dtype="object")
ciudades[:,0] = nombre_ciudades
ciudades[:,1] = id_ciudades
ciudades[:,2] = bin_ciudades
ciudades[:,3] = np.zeros((nombre_ciudades.shape[0]))
print(ciudades)

[['Mexico City' 0 '000' 0.0]
 ['Merida' 1 '001' 0.0]
 ['Buenos Aires' 2 '010' 0.0]
 ['Quito' 3 '011' 0.0]
 ['Washington D.C.' 4 '100' 0.0]
 ['New York' 5 '101' 0.0]
 ['Miami' 6 '110' 0.0]
 ['Monterrey' 7 '111' 0.0]
 ['Panama City' 8 '1000' 0.0]
 ['San Salvador' 9 '1001' 0.0]
 ['Managua' 10 '1010' 0.0]
 ['Brazilia' 11 '1011' 0.0]
 ['Mendoza' 12 '1100' 0.0]
 ['Caracas' 13 '1101' 0.0]
 ['Montevideo' 14 '1110' 0.0]
 ['Guadalajara' 15 '1111' 0.0]
 ['Boston' 16 '10000' 0.0]
 ['Bogotá' 17 '10001' 0.0]]


## Matriz de distancias

In [5]:
# número de ciudades
n = len(df_ciudades)
matriz_distancias = np.zeros((n,n))

for i in range(n):
    for j in range(n):
        if i != j:
            matriz_distancias[i,j] = get_distancia(df_ciudades['Latitud'][i],df_ciudades['Longitud'][i],
                                          df_ciudades['Latitud'][j],df_ciudades['Longitud'][j])
            

distancias_matrix = pd.DataFrame(matriz_distancias, columns=df_ciudades['Ciudad'], index = df_ciudades['Ciudad'])

In [6]:
display(distancias_matrix)

Ciudad           Mexico City       Merida  Buenos Aires        Quito  \
Ciudad                                                                 
Mexico City         0.000000  1009.959843   7392.178684  3135.709015   
Merida           1009.959843     0.000000   7004.211339  2644.150812   
Buenos Aires     7392.178684  7004.211339      0.000000  4360.060643   
Quito            3135.709015  2644.150812   4360.060643     0.000000   
Washington D.C.  3031.811604  2327.565260   8396.527908  4348.827501   
New York         3359.383041  2643.050506   8526.194114  4569.460001   
Miami            2065.272960  1097.212425   7094.952486  2890.594533   
Monterrey         705.925938  1213.520720   8028.590573  3711.248568   
Panama City      2408.857647  1715.030837   5333.037977  1025.530802   
San Salvador     1233.956557   809.861482   6280.332978  1944.679440   
Managua          1600.957943  1047.292813   5968.507501  1613.735904   
Brazilia         6835.065741  6116.463263   2334.403612  3776.161246   
Mendoza          6648.609671  6381.173335    985.614665  3774.047997   
Caracas          3595.449156  2689.070020   5093.044534  1743.741681   
Montevideo       7554.599238  7144.536815    205.232076  4501.636863   
Guadalajara       461.067374  1429.853511   7766.608993  3562.151769   
Boston           3665.482788  2941.198434   8654.780454  4788.167318   
Bogotá           3170.731318  2464.943628   4670.520317   730.923189   

Ciudad           Washington D.C.     New York        Miami    Monterrey  \
Ciudad                                                                    
Mexico City          3031.811604  3359.383041  2065.272960   705.925938   
Merida               2327.565260  2643.050506  1097.212425  1213.520720   
Buenos Aires         8396.527908  8526.194114  7094.952486  8028.590573   
Quito                4348.827501  4569.460001  2890.594533  3711.248568   
Washington D.C.         0.000000   327.582714  1491.176569  2623.500270   
New York              327.582714     0.000000  1757.961225  2945.076096   
Miami                1491.176569  1757.961225     0.000000  2013.994655   
Monterrey            2623.500270  2945.076096  2013.994655     0.000000   
Panama City          3336.690529  3570.004517  1867.122418  2876.282439   
San Salvador         3048.362836  3348.328915  1639.742840  1766.700637   
Managua              3114.733025  3397.166346  1644.533412  2111.060860   
Brazilia             6797.691847  6839.011011  5794.758090  7310.080266   
Mendoza              8028.085133  8201.327390  6631.402300  7315.684383   
Caracas              3317.116974  3433.343519  2200.658515  3898.681265   
Montevideo           8483.304262  8603.779701  7204.245436  8184.245928   
Guadalajara          3229.236038  3554.283691  2430.007251   639.142332   
Boston                633.671486   306.108494  2025.336834  3245.755067   
Bogotá               3814.195109  4003.222959  2429.837957  3640.297547   

Ciudad           Panama City  San Salvador      Managua     Brazilia  \
Ciudad                                                                 
Mexico City      2408.857647   1233.956557  1600.957943  6835.065741   
Merida           1715.030837    809.861482  1047.292813  6116.463263   
Buenos Aires     5333.037977   6280.332978  5968.507501  2334.403612   
Quito            1025.530802   1944.679440  1613.735904  3776.161246   
Washington D.C.  3336.690529   3048.362836  3114.733025  6797.691847   
New York         3570.004517   3348.328915  3397.166346  6839.011011   
Miami            1867.122418   1639.742840  1644.533412  5794.758090   
Monterrey        2876.282439   1766.700637  2111.060860  7310.080266   
Panama City         0.000000   1179.637483   812.486225  4440.058794   
San Salvador     1179.637483      0.000000   367.803223  5601.769099   
Managua           812.486225    367.803223     0.000000  5236.308661   
Brazilia         4440.058794   5601.769099  5236.308661     0.000000   
Mendoza          4791.336430   5613.686901  5333.8

Cruce CX
* cruce de 2 padres y mantiene la posición de ciertos valores que se heredan de forma ciclica

In [18]:
import random

def cruce_cx(p1,p2, target_col=0):
    # Aseguramos que ambos padres tengan el mismo tamaño
    size = len(p1)
    
    # inicialización del hijo con valores None
    offspring = [None] * size

    #punto de inicio aleatorio
    start = random.randint(0, size - 1)
    
    #guarda  el ciclo de los índices que serán intercambiados
    indices = []
    
    # Iniciamos el ciclo con el valor del gen en el punto de inicio
    current_index = start
    while current_index not in indices:
        indices.append(current_index)
        # Encuentra la posición en el otro padre del valor actual del primer padre
        current_index = p2.index(p1[current_index])
    
    # rellena  los valores del ciclo desde el primer padre
    for index in indices:
        offspring[index] = p1[index]

    # completa  el resto con los valores del segundo padre
    for i in range(size):
        if offspring[i] is None:
            offspring[i] = p2[i]
    
    return offspring

# Ejemplo de uso
p1 = [1, 2, 3, 4, 5, 6, 7, 8]
p2 = [4, 1, 2, 8, 7, 6, 3, 5]

hijo = cruce_cx(p1, p2)
print("Padre 1:", p1)
print("Padre 2:", p2)
print("Hijo:   ", hijo)


Padre 1: [1, 2, 3, 4, 5, 6, 7, 8]
Padre 2: [4, 1, 2, 8, 7, 6, 3, 5]
Hijo:    [1, 2, 3, 4, 5, 6, 7, 8]


In [19]:
import numpy as np
import random

def cruce_cx2(parents_slice):
    p1 = parents_slice[0]
    p2 = parents_slice[1]

    size = len(p1)

    # Initialize offspring with None values
    offspring = np.full(size, None)

    # Random start index
    start = random.randint(0, size - 1)

    # List to store cycle indices
    indices = []

    current_index = start
    while current_index not in indices:
        indices.append(current_index)
        # Position in p2 of the current value in p1
        current_index = np.where(p2 == p1[current_index])[0][0]

    # Fill offspring with values from p1 (cycle)
    for index in indices:
        offspring[index] = p1[index]

    # Complete the rest with values from p2
    for i in range(size):
        if offspring[i] is None:
            offspring[i] = p2[i]

    return offspring

Mutación Scramble

In [20]:
def mutacion_scramble(individuo):
    n_cromos = len(individuo)
    
    # selección de dos indices aleatorios
    idx1,idx2 = np.sort(np.random.choice(range(n_cromos),size=2,replace=False))
    # segmento a mutar 
    scramble_part = individuo[idx1:idx2+1]
    print(f'subrista:{scramble_part}')

    # desorden del segmente
    np.random.shuffle(scramble_part)
    print(f'subrista shuffle:{scramble_part}')
    
    # selección de un índice aleatorio para insertar la parte mutada 
    
    #reemplazo de la parte del individuo con el segmento desordenado
    individuo[idx1:idx2+1] = scramble_part

    return individuo 

In [23]:
# Ejemplo: Si tienes una población de 100 individuos, cada uno con 18 genes
population_size = 100
gene_length = 18

# Generamos una población inicial aleatoria de 100 individuos con permutaciones de 18 genes
population = [np.random.permutation(gene_length) for _ in range(population_size)]

# mutación por scramble a cada individuo en la población
mutation_rate = 0.1  # Probabilidad de mutación

for i in range(population_size):
    if np.random.rand() < mutation_rate:  # Aplica la mutación con una cierta probabilidad
        print(f"antes de la mutación {i}: {population[i]}")
        population[i] = mutacion_scramble(population[i])
        print(f"después de la mutación {i}: {population[i]}")

antes de la mutación 14: [4 3 1 0 2]
subrista:[1 0 2]
subrista shuffle:[2 0 1]
después de la mutación 14: [4 3 2 0 1]
antes de la mutación 26: [4 0 1 3 2]
subrista:[4 0]
subrista shuffle:[4 0]
después de la mutación 26: [4 0 1 3 2]
antes de la mutación 28: [4 1 3 0 2]
subrista:[3 0]
subrista shuffle:[3 0]
después de la mutación 28: [4 1 3 0 2]
antes de la mutación 41: [3 2 4 1 0]
subrista:[2 4 1 0]
subrista shuffle:[4 1 2 0]
después de la mutación 41: [3 4 1 2 0]


In [49]:
# esta función ya realiza la separación adecuada para las tercias sin importar si 
# es par o no la longitud de los cromosoams 
def cruce_dos_corte(padres):
    n_cromos = len(padres[0, 2])
    p1 = padres[0, 2]
    p2 = padres[1, 2]

    # Convertimos las cadenas de cromosomas en listas de genes
    p1 = list(map(str, p1))  # Convertir a lista de caracteres
    p2 = list(map(str, p2))

    # calcula la longitud de cada parte
    part_length = n_cromos // 3
    remaining = n_cromos % 3

    # divide los cromosomas en tres partes 
    parts_p = []
    parts_m = []
    start = 0
    for i in range(3):
        end = start + part_length
        if i < remaining:
            end += 1
        parts_p.append(p1[start:end])
        parts_m.append(p2[start:end])
        start = end

    h1 = f"{parts_m[0]}{parts_p[1]}{parts_m[2]}"
    h2 = f"{parts_p[0]}{parts_m[1]}{parts_p[2]}"

    return h1, h2

In [39]:
# sólo para cuando son de dos digitos los genes 
def cruce_dos_corte3(padres, gene_length=2):
    n_cromos = len(padres[0, 2])
    p1 = padres[0, 2]
    p2 = padres[1, 2]

    # Convertimos las cadenas de cromosomas en listas de genes
    p1 = [p1[i:i+gene_length] for i in range(0, n_cromos, gene_length)]
    p2 = [p2[i:i+gene_length] for i in range(0, n_cromos, gene_length)]

    # calcula la longitud de cada parte
    part_length = len(p1) // 3
    remaining = len(p1) % 3

    # divide los cromosomas en tres partes 
    parts_p = []
    parts_m = []
    start = 0
    for i in range(3):
        end = start + part_length
        if i < remaining:
            end += 1
        parts_p.append(p1[start:end])
        parts_m.append(p2[start:end])
        start = end

    h1 = f"{parts_m[0]}{parts_p[1]}{parts_m[2]}"
    h2 = f"{parts_p[0]}{parts_m[1]}{parts_p[2]}"

    return h1, h2

pruebas 

In [4]:
population_size = 100
gene_length = 18

# Generamos una población inicial de 100 individuos, cada uno con 18 genes
population = [np.random.permutation(gene_length) for _ in range(population_size)]

In [5]:
population

[array([16,  1,  8, 12,  9, 10,  5, 15, 17, 11,  4,  3,  7,  0, 14, 13,  2,
         6]),
 array([11,  5, 17, 12,  4,  3, 10, 15,  2,  8, 16,  0, 14,  1,  7,  9,  6,
        13]),
 array([16,  1,  6, 11,  0, 17, 10,  5, 13,  4,  7, 12,  3, 14, 15,  9,  8,
         2]),
 array([11,  5,  6,  8, 12,  2,  9,  0,  7,  4,  3, 14, 15, 16, 13,  1, 10,
        17]),
 array([ 1,  2, 12, 15,  8, 13, 10, 14, 16,  3,  0,  7, 17,  6,  5,  9,  4,
        11]),
 array([ 3,  8, 14, 15,  9, 11, 17,  2,  1,  6, 16,  0,  5, 13, 12,  4,  7,
        10]),
 array([ 8,  7,  4, 15, 10,  1,  5, 16,  0, 17, 13,  3,  6,  9,  2, 14, 12,
        11]),
 array([16, 11,  5,  0,  9, 12,  1, 13,  4,  7,  6, 17, 15,  2, 14,  3,  8,
        10]),
 array([ 1,  6,  7,  3, 15, 14,  8, 10,  9,  2, 13,  0, 17, 11, 16, 12,  5,
         4]),
 array([11,  0, 13,  6,  4,  9, 14, 16,  3,  8,  2, 17,  1, 15, 12,  7,  5,
        10]),
 array([12, 10, 13,  7,  8, 16,  1,  9, 11,  2,  6,  5,  3,  4, 14,  0, 15,
        17]),
 array([ 9

In [6]:
def cruce_cx(padres):
    """
    Realiza un cruce CX (Cyclic Crossover) en la población con numpy arrays.

    Args:
    padres: Un arreglo numpy de dos dimensiones que contiene dos individuos (padres).
            Cada padre es un vector de cromosomas (genes).

    Returns:
    offspring1: Primer hijo resultado del cruce.
    offspring2: Segundo hijo resultado del cruce.

    """
    p1 = padres[0, 0]
    p2 = padres[1, 0]

    if len(p1) != len(p2):
        raise Exception("Los padres no tienen la misma cantidad de cromosomas")

    p1 = np.array(list(p1)).astype(int)
    p2 = np.array(list(p2)).astype(int)

    # print(f"Padre 1: {p1}")
    # print(f"Padre 2: {p2}")

    # n_cromos = len(p1)

    size = len(p1)
    offspring1 = np.full(size, -1)
    offspring2 = np.full(size, -1)

    # diccionario para los indices ciclados
    p2_indices = {val: idx for idx, val in enumerate(p2)}
    print(p2_indices)
    # posiciones para el cx, permutaciones
    start = 0
    while -1 in offspring1:
        if offspring1[start] == -1:
            cycle_indices = []
            current = start

            # inicio del ciclo
            while current not in cycle_indices:
                cycle_indices.append(current)
                current_value = p1[current]
                # índice para el padre 2
                current = p2_indices[current_value]

            # intercambio de los valores según el ciclo que se haya encontrado
            for index in cycle_indices:
                offspring1[index] = p1[index]
                offspring2[index] = p2[index]

            # cambia el ciclo de los restantes
            # start += 1
            start = np.where(offspring1 == -1)[0]

    # se llena el resto d elos valores que no están en el ciclo
    for i in range(size):
        if offspring1[i] == -1:
            offspring1[i] = p2[i]
        if offspring2[i] == -1:
            offspring2[i] = p1[i]

    print(f"Hijo 1: {offspring1}")
    print(f"Hijo 2: {offspring2}")
    return offspring1, offspring2

In [7]:
def mutacion_scramble(individual, cromosomas_mutation=None, funcion_aptitud=None):
    """
    Realiza la mutación scramble en un individuo (TSP), insertando la subsección mezclada en una posición diferente.

    Args:
        individual: Un array de NumPy que representa el orden de visita de las ciudades.
        cromosomas_mutation: Tamaño de la subsección a mutar.

    Returns:
        Un nuevo array con el individuo mutado.
    """
    # print(f'individuo original: {individual}')
    n = len(individual)
    # print(f'número de mutaciones: {cromosomas_mutation}')
    if not cromosomas_mutation:
        cromosomas_mutation = n // 2
    else:
        cromosomas_mutation = int(cromosomas_mutation)
        if cromosomas_mutation > (n // 2):
            raise ValueError(
                "La cantidad de genes a mutar no debe pasar la mitad de los cromosomas del individuo"
            )
    # Selección de un índice aleatorio para el inicio del segmento a mutar
    # idx1 = np.random.randint(0, n - cromosomas_mutation + 1)
    n_ = (n + 1) - cromosomas_mutation
    idx1 = np.random.randint(0, n_)
    idx2 = idx1 + cromosomas_mutation
    # print(f'índices de mutación: {idx1}, {idx2}')

    # Segmento a mutar
    scramble_part = individual[idx1 : idx2 + 1]
    # print(f'sublista original: {scramble_part}')

    # Desordena el segmento
    np.random.shuffle(scramble_part)
    # print(f'sublista desordenada: {scramble_part}')

    # Crea una nueva versión del individuo sin la subsección
    new_individual = np.concatenate((individual[:idx1], individual[idx2 + 1 :]))
    # print(f'individuo sin la sublista: {new_individual}')

    # Selecciona un índice para insertar el segmento más adelante
    new_insert_idx = np.random.randint(idx1 + 1, n - cromosomas_mutation + 1)
    # print(f'nuevo índice de inserción: {new_insert_idx}')

    # Inserta el segmento desordenado en la nueva posición
    new_individual = np.concatenate(
        (
            new_individual[:new_insert_idx],
            scramble_part,
            new_individual[new_insert_idx:],
        )
    )
    # print(f'individuo mutado: {new_individual}')
    new_mutante = np.zeros(4, dtype="object")
    new_mutante[0] = new_individual
    new_mutante[2] = " ".join([chr(c + 64) for c in new_individual])
    new_mutante[3] = funcion_aptitud(np.array([new_mutante]))[0]
    return new_mutante, idx1