In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import plotly.graph_objects as go
import time
import os
import pickle

from my_lib.utility import *

## Actividad 3: Algoritmo genético para resolver el problema del viajero frecuente

El problema es de tipo TSP con 18 ciudades del conteninte Americano. Por lo tanto existen $18!\$ soluciones posibles ($6402373705728000$), dada el basto espacio de busqueda la población de individuos se debe limitar a minimo 100 y máximo 500.

> Criterios para la evaluación
> - Implementar 2 métodos de cruza, PMX y algún otro método como OX o CX
> - Implementar 2 métodos de mutación, Scramble y Heuristic
> - Implementar un método de selección, cualquiera de los ya vistos
> - Implementar un método hibrido de paro
> - Implementar un méotodo elitista
> - Realizar las comparaciones y la discusión de los resultados

# Codificación del dominio

In [2]:
nombre_ciudades = np.array(["Mexcio", "Miami", "Quito", "San Salvador", "Mendoza","Guadalajara"])

id_ciudades = np.arange(nombre_ciudades.shape[0])
bin_ciudades = binarizar(datos=id_ciudades,nbites=3)

ciudades = np.zeros((nombre_ciudades.shape[0],4),dtype="object")
ciudades[:,0] = nombre_ciudades
ciudades[:,1] = id_ciudades
ciudades[:,2] = bin_ciudades
ciudades[:,3] = np.zeros((nombre_ciudades.shape[0]))
print(ciudades)

[['Mexcio' 0 '000' 0.0]
 ['Miami' 1 '001' 0.0]
 ['Quito' 2 '010' 0.0]
 ['San Salvador' 3 '011' 0.0]
 ['Mendoza' 4 '100' 0.0]
 ['Guadalajara' 5 '101' 0.0]]


## Matriz de distancias

In [3]:
# Matriz de disntancias

distancias = np.array(
    [
        [0, 2270.05, 3714.66, 1778.27, 7223.16, 337.03],
        [2270.05, 0, 2882.57, 1627.62, 6578.78, 2425.29],
        [3714.66, 2882.57, 0, 1938.05, 3780.05, 3551.96],
        [1778.27, 1627.62, 1938.05, 0, 5567.96, 1681.97],
        [7223.16, 6578.78, 3780.05, 5567.96, 0, 6971.44],
        [337.03, 2425.29, 3551.96, 1681.97, 6971.44, 0],
    ]
)

print(distancias)

[[   0.   2270.05 3714.66 1778.27 7223.16  337.03]
 [2270.05    0.   2882.57 1627.62 6578.78 2425.29]
 [3714.66 2882.57    0.   1938.05 3780.05 3551.96]
 [1778.27 1627.62 1938.05    0.   5567.96 1681.97]
 [7223.16 6578.78 3780.05 5567.96    0.   6971.44]
 [ 337.03 2425.29 3551.96 1681.97 6971.44    0.  ]]


# Generación de población

Para poder realizar una buena comparación con las distintas combinaciones de operadores genéticos se trabajará con 5 poblaciones iniciales, las cuales son las mismas parar cada experimento


Si ya existe el archivo de poblaciones no hay necesidad de crear nuevamente las poblaciones iniciales

In [4]:
POB_FILE = "files\poblaciones_2.pkl"

In [5]:
def get_poblaciones_iniciales(n=5, tam_pob=60):
    """
    Genera y carga las poblaciones iniciales para un algoritmo genético.

    Si el archivo de poblaciones no existe, la función lo crea generando las poblaciones iniciales y guardándolas en el archivo.
    Si el archivo ya existe, la función lo carga y devuelve las poblaciones.

    Parámetros:
        n (int): Número de poblaciones iniciales a generar (por defecto, 5).
        tam_pob (int): Tamaño de cada población (por defecto, 60).

    Valor de retorno:
        list: Lista de poblaciones iniciales, donde cada población es una matriz de numpy con 4 columnas: ruta, aptitud, individuo y aptitud.
    """
    poblaciones = []
    POB_PATH = os.path.join("..", POB_FILE)
    if not os.path.exists(POB_PATH):
        print("El archivo de poblaciones no existse, creando archivo")
        
        for i in range(n):
            recorrido = generar_poblacion_perm(ciudades, tam_pob)
            
            poblacion = np.zeros((recorrido.shape[0], 4), dtype="object")
            poblacion[:, 0] = [c.astype(int) for c in recorrido]  # Ruta
            poblacion[:, 1] = np.ones((recorrido.shape[0]))
            poblacion[:, 2] = [individuo_toString(c.astype(int)) for c in recorrido]
            poblacion[:, 3] = np.zeros((recorrido.shape[0]))  # Aptitud
        
            poblaciones.append(poblacion)
        
        try:
            with open(POB_PATH, "wb") as f:
                pickle.dump(poblaciones,f)
            print("Archivo de poblaciones creado correctamente")
        except Exception as e:
            print(f"Error al guardar archivo: {e}")
            
    else:
        try:
            with open(POB_PATH, "rb") as f:
                poblaciones = pickle.load(f)
            print("Archivo de poblaciones cargado correctamente")
        except Exception as e:
            print(f"Error al cargar archivo: {e}")
    
    return poblaciones

In [6]:
pobs = get_poblaciones_iniciales(n=5,tam_pob=80)
print(len(pobs))

Archivo de poblaciones cargado correctamente
5


# Función objetivo

In [7]:
def y(ciudad1,ciudad2):
    return distancias[ciudad1,ciudad2]

def evaluar(poblacion):
    evaluacion = np.zeros((poblacion.shape[0]))
    for idx,fila in enumerate(poblacion):
        individuo = fila[0]
        n = len(individuo) - 1
        aptitud = 0
        
        for i in range (n,-1,-1):
            c1 = int(individuo[i]) #Id de la ciudad
            c2 = int(individuo[i-1])
            distancia = y(c1,c2)
            aptitud += distancia
           # print(f"Distancia entre {ciudades[c1]} y {ciudades[c2]}: {distancia}")
        evaluacion[idx] = np.around(aptitud,4)
        
    return evaluacion



# Experimento combinacion PMX, y Heuristic mutation

En este experimento a partir de la población incial, tomar en cuenta que hay 5 poblaciones inciales con las cuales debe realizarse el experimento, se obtienen nuevas generaciones de individuos y una vez alcanza el 80% de individuos aptos, esto quiere decir que los individuso deben superar más del 0.8 de aptitud, o se llega un 10 generaciones el algoritmo se detiene.

**Condiciones de termino:**

* Epsilon:
    * Cuando el 80% de la población alcanza una aptitud mayor de 0.8
* Generaciones:
    * Cuando se llega a la generación número 10

**Operadores:**
* Método de competencia genética para la creación de las poblaciones
* Operador de selección *Ruleta*
* Operador de cruce *PMX*
* Operador de mutación  *Hueristico*

## Evaluar y Ordenar la poblacion

La función de ordenar población ordena de mayor a menor.

Este problema es un problema para encontrar las rutas con menor costo

In [8]:
MAX_GEN = 10

In [17]:
#Tiempo del experimento total
start_exp_time = time.time()
for i in range(len(pobs)): 
    #Cargar población incial
    print(f"Población inicial: {i}")
    poblacion = pobs[i]
    #evaluar la población
    pob_aptitud = evaluar(poblacion)
    poblacion[:,3] = pob_aptitud
    #La población esta ordenada de mayor a menor, por lo tanto los últimos indiviudos siempre son los más aptos 
    poblacion = ordenar_poblacion(poblacion)
    

    # print(poblacion.shape)
    # print(poblacion[-10:])
    
    
    #Experimentación
    GEN = 0
    GENERACIONES = []
    HISTDF = []
     
    GENERACIONES.append(poblacion)
    
    start_time = time.time()
    while True:
        #poblacion actual
        print(np.mean(poblacion[:,3]))
        if GEN >= MAX_GEN or paro_epsilon(poblacion,14000,0.9,opt=1):
            print("Convergencia alcanzada")
            break
        
        else:
            
            #Obtener siguiente generacion
            #Selección y cruza
            hijos = get_next_gen(poblacion,op_seleccion=0,op_cruza=0)
            print(hijos)
            
            GEN += 1
            
            
            
    end_time = time.time()
    elapsed_time = start_time - end_time
    print(f"Tiempo de ejecucion iteracion {i}: {elapsed_time} segundos")
    break


end_exp_time = time.time()
elapsed_exp_time = end_exp_time - start_exp_time

Población inicial: 0
20907.188374999994
[['430415', array(['032415', '430251'], dtype=object)], ['032251', array(['032415', '430251'], dtype=object)], ['210513', array(['204513', '210345'], dtype=object)], ['204345', array(['204513', '210345'], dtype=object)], ['413042', array(['315042', '413052'], dtype=object)], ['315052', array(['315042', '413052'], dtype=object)], ['314014', array(['253014', '314052'], dtype=object)], ['253052', array(['253014', '314052'], dtype=object)], ['013214', array(['305214', '013524'], dtype=object)], ['305524', array(['305214', '013524'], dtype=object)], ['513520', array(['143520', '513024'], dtype=object)], ['143024', array(['143520', '513024'], dtype=object)], ['351542', array(['103542', '351042'], dtype=object)], ['103042', array(['103542', '351042'], dtype=object)], ['320403', array(['152403', '320154'], dtype=object)], ['152154', array(['152403', '320154'], dtype=object)], ['230145', array(['320145', '230154'], dtype=object)], ['320154', array(['32014

KeyboardInterrupt: 

In [10]:
print(f"Tiempo de experimentación: {elapsed_exp_time}")

Tiempo de experimentación: 0.005994319915771484
