In [30]:
import numpy as np

from my_lib.utility import *

In [31]:
aux = generar_poblacion_perm([1,2,3,4,5],60)
aux

array([[2., 0., 1., 3., 4.],
       [1., 3., 0., 4., 2.],
       [1., 3., 2., 4., 0.],
       [1., 4., 0., 2., 3.],
       [0., 2., 1., 3., 4.],
       [3., 4., 1., 0., 2.],
       [2., 0., 3., 4., 1.],
       [0., 3., 2., 1., 4.],
       [2., 4., 0., 1., 3.],
       [4., 2., 0., 3., 1.],
       [2., 1., 4., 0., 3.],
       [1., 3., 0., 4., 2.],
       [4., 3., 2., 1., 0.],
       [3., 1., 2., 4., 0.],
       [2., 3., 0., 1., 4.],
       [0., 3., 4., 1., 2.],
       [2., 3., 4., 1., 0.],
       [0., 4., 3., 1., 2.],
       [4., 1., 3., 2., 0.],
       [3., 0., 2., 4., 1.],
       [0., 3., 2., 4., 1.],
       [1., 3., 4., 0., 2.],
       [1., 4., 3., 2., 0.],
       [1., 0., 2., 4., 3.],
       [1., 3., 0., 4., 2.],
       [0., 4., 1., 3., 2.],
       [1., 2., 0., 3., 4.],
       [0., 2., 3., 1., 4.],
       [0., 3., 4., 2., 1.],
       [1., 3., 2., 0., 4.],
       [0., 1., 3., 2., 4.],
       [0., 3., 1., 2., 4.],
       [3., 2., 1., 0., 4.],
       [4., 3., 2., 0., 1.],
       [4., 1.

In [32]:
p1 = np.array([1,2,3,4,5,6,7,8,9])
p2 = np.array([8,5,7,1,2,4,9,3,6])

px1 = 2
px2 = 5

print(p1[px1:px2])
print(p2[px1:px2])

aux_c = []
print(p2)

h1 = [p2[:px1],p1[px1:px2],p1[px2:]]
h1 = np.concatenate(h1)
print(h1)
for i in range(px2,len(p1)+px2):
    
    idx = i-len(p1)
    if p2[idx] not in p1[px1:px2]:
        aux_c.append(p2[idx])
    
for i in range(px2,len(p1)+px1):
    print(h1[i-len(p1)])

[3 4 5]
[7 1 2]
[8 5 7 1 2 4 9 3 6]
[8 5 3 4 5 6 7 8 9]
6
7
8
9
8
5


In [33]:
nombre_ciudades = np.array(["Mexcio", "Miami", "Quito"])

id_ciudades = np.arange(nombre_ciudades.shape[0])
bin_ciudades = binarizar(datos=id_ciudades, nbites=3)

ciudades = np.zeros((nombre_ciudades.shape[0], 4), dtype="object")
ciudades[:, 0] = nombre_ciudades
ciudades[:, 1] = id_ciudades
ciudades[:, 2] = bin_ciudades
ciudades[:, 3] = np.zeros((nombre_ciudades.shape[0]))
print(ciudades)

[['Mexcio' 0 '000' 0.0]
 ['Miami' 1 '001' 0.0]
 ['Quito' 2 '010' 0.0]]


In [34]:
distancias = np.array(
    [
        [0, 2270.05, 3714.66, 1778.27, 7223.16],
        [2270.05, 0, 2882.57, 1627.62, 6578.78],
        [3714.66, 2882.57, 0, 1938.05, 3780.05],
        [1778.27, 1627.62, 1938.05, 0, 5567.96],
        [7223.16, 6578.78, 3780.05, 5567.96, 0],
    ]
)

print(distancias)

[[   0.   2270.05 3714.66 1778.27 7223.16]
 [2270.05    0.   2882.57 1627.62 6578.78]
 [3714.66 2882.57    0.   1938.05 3780.05]
 [1778.27 1627.62 1938.05    0.   5567.96]
 [7223.16 6578.78 3780.05 5567.96    0.  ]]


In [35]:
recorrido = np.array([[0,1,2],
                [0,2,1],
                [1,0,2],
                [1,2,0],
                [2,0,1],
                [2,1,0]])
poblacion = np.zeros((recorrido.shape[0],4),dtype="object")
poblacion[:,0] = [c.astype(int) for c in recorrido] #Ruta
poblacion[:,1] = np.ones((recorrido.shape[0]))
poblacion[:,2] = [individuo_toString(c.astype(int)) for c in recorrido]
poblacion[:,3] = np.zeros((recorrido.shape[0])) #Aptitud

print(poblacion)
print(poblacion.shape)

[[array([0, 1, 2]) 1.0 '012' 0.0]
 [array([0, 2, 1]) 1.0 '021' 0.0]
 [array([1, 0, 2]) 1.0 '102' 0.0]
 [array([1, 2, 0]) 1.0 '120' 0.0]
 [array([2, 0, 1]) 1.0 '201' 0.0]
 [array([2, 1, 0]) 1.0 '210' 0.0]]
(6, 4)


In [49]:
def y(ciudad1,ciudad2):
    return distancias[ciudad1,ciudad2]

def evaluar(poblacion):
    evaluacion = np.zeros((poblacion.shape[0]))
    print(poblacion)
    print("___________________________")
    for idx,fila in enumerate(poblacion):
        individuo = fila[0]
        n = len(individuo) - 1
        aptitud = 0
        
        for i in range (n,-1,-1):
            
            c1 = int(individuo[i]) #Id de la ciudad
            c2 = int(individuo[i-1])
            
            distancia = y(c1,c2)
            aptitud += distancia
            
            
            print(c1,c2,distancia)
            #print(f"Distancia entre {ciudades[c1]} y {ciudades[c2]}: {distancia}")
        evaluacion[idx] = np.around(aptitud,4)
        print(aptitud)
        print("___________________________")
    return evaluacion

pob_aptitud = evaluar(poblacion)
pob_aptitud

[[array([0, 1, 2]) 1.0 '012' 0.0]
 [array([0, 2, 1]) 1.0 '021' 0.0]
 [array([1, 0, 2]) 1.0 '102' 0.0]
 [array([1, 2, 0]) 1.0 '120' 0.0]
 [array([2, 0, 1]) 1.0 '201' 0.0]
 [array([2, 1, 0]) 1.0 '210' 0.0]]
___________________________
2 1 2882.57
1 0 2270.05
0 2 3714.66
8867.28
___________________________
1 2 2882.57
2 0 3714.66
0 1 2270.05
8867.279999999999
___________________________
2 0 3714.66
0 1 2270.05
1 2 2882.57
8867.28
___________________________
0 2 3714.66
2 1 2882.57
1 0 2270.05
8867.279999999999
___________________________
1 0 2270.05
0 2 3714.66
2 1 2882.57
8867.28
___________________________
0 1 2270.05
1 2 2882.57
2 0 3714.66
8867.28
___________________________


array([8867.28, 8867.28, 8867.28, 8867.28, 8867.28, 8867.28])